server:
  port: 8080
  servlet:
    context-path: /professionalBank
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/db_bankManager?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
      host: localhost
      port: 6378
      password: tyt
      timeout: 2000
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
    #mybatis 大小写转驼峰


mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.tyt.bankmanagersystem.mapper.UserMapper: debug
bank-admin:
  admin-username: tyt
  password: tyt

minio:
  endpoint: http://localhost:9000
  access-key: miniotyt
  secret-key: miniotyt
  bucket-name: bank-manager-system-bucket


