spring:
  datasource:
    url: jdbc:mysql://47.94.208.1:3306/db_bankManager?serverTimezone=UTC&useSSL=false
    username: root
    password: tYt2004128@qq.com
  redis:
    host: 47.94.208.1
    port: 6378
    password: tyt

minio:
  endpoint: http://47.94.208.1:9000
  access-key: miniotyt
  secret-key: miniotyt
  bucket-name: bank-manager-system-bucket