server:
  port: 8080
  servlet:
    context-path: /professionalBank
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345
    username: root
    url: jdbc:mysql://localhost:3306/db_bankManager
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
      database: 0
      host: 127.0.0.1
      port: 6378
      timeout: 2000
      password: tyt
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
    #mybatis 大小写转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.tyt.bankmanagersystem.mapper.UserMapper: debug
bank-admin:
  admin-username: tyt
  password: tyt



